# Generated by Django 5.2.5 on 2025-08-17 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(choices=[('001', 'Banco do Brasil S.A.'), ('033', 'Banco Santander (Brasil) S.A.'), ('104', 'Caixa Econômica Federal'), ('237', 'Banco Bradesco S.A.'), ('260', 'Nu Pagamentos S.A. (Nubank)'), ('323', 'Mercado Pago - Banco MercadoPago de Pagamentos S.A.'), ('336', 'Banco C6 S.A. (C6 Bank)'), ('341', 'Itaú Unibanco S.A.'), ('380', 'PicPay Bank S.A.'), ('077', 'Banco Inter S.A.'), ('655', 'Banco Votorantim S.A. (Neon)'), ('212', 'Banco Original S.A.'), ('746', 'Banco Modal S.A.'), ('623', 'Banco Pan S.A.'), ('069', 'Banco Crefisa S.A.'), ('070', 'Banco de Brasília S.A. (BRB)'), ('748', 'Banco Cooperativo Sicredi S.A.'), ('756', 'Banco Cooperativo do Brasil S.A. (Sicoob)'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('ELO', 'Elo'), ('HIPERCARD', 'Hipercard'), ('DINERS', 'Diners Club International'), ('DISCOVER', 'Discover'), ('JCB', 'JCB (Japan Credit Bureau)'), ('VALECARD', 'Valecard'), ('ALELO', 'Alelo'), ('SODEXO', 'Sodexo'), ('TICKET', 'Ticket (Edenred)'), ('VR', 'VR Benefícios'), ('BANESCARD', 'Banescard Alimentação'), ('GREENCARD', 'Green Card')], max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_conta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('alimentacao', 'Cartão Alimentação')], default='corrente', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_proprietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição da Entrada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Recebimento')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local/Origem')),
                ('forma_recebimento', models.CharField(choices=[('dinheiro', 'Dinheiro (Caixa)'), ('pix', 'PIX'), ('ted_doc', 'TED/DOC'), ('cartao', 'Cartão (Crédito/Débito)'), ('boleto', 'Boleto'), ('outros', 'Outros')], default='dinheiro', max_length=20, verbose_name='Forma de Recebimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contabancaria', verbose_name='Conta Bancária')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_lancamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Lançamento')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('categoria', models.CharField(choices=[('moradia', 'Moradia'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('seguros', 'Seguros'), ('pessoais', 'Despesas Pessoais'), ('familia', 'Família'), ('contas', 'Contas e Serviços'), ('investimentos', 'Investimentos'), ('impostos', 'Impostos')], max_length=20, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, choices=[('moradia_aluguel', 'Aluguel'), ('moradia_financiamento', 'Financiamento Imobiliário'), ('moradia_condominio', 'Condomínio'), ('moradia_iptu', 'IPTU'), ('moradia_energia', 'Energia Elétrica'), ('moradia_agua', 'Água e Esgoto'), ('moradia_gas', 'Gás'), ('moradia_internet', 'Internet'), ('moradia_manutencao', 'Manutenção/Reparos'), ('alimentacao_supermercado', 'Supermercado'), ('alimentacao_hortifruti', 'Hortifruti'), ('alimentacao_padaria', 'Padaria'), ('alimentacao_restaurante', 'Restaurante'), ('alimentacao_lanches', 'Lanches'), ('transporte_combustivel', 'Combustível'), ('transporte_manutencao', 'Manutenção Veicular'), ('transporte_seguro', 'Seguro Veicular'), ('transporte_estacionamento', 'Estacionamento'), ('transporte_publico', 'Transporte Público'), ('transporte_app', 'Táxi/App de Transporte'), ('saude_plano', 'Plano de Saúde'), ('saude_medicamentos', 'Medicamentos'), ('saude_consultas', 'Consultas Médicas'), ('saude_exames', 'Exames'), ('saude_odontologia', 'Odontologia'), ('educacao_mensalidade', 'Mensalidade Escolar/Faculdade'), ('educacao_cursos', 'Cursos/Treinamentos'), ('educacao_materiais', 'Livros/Material Didático'), ('lazer_cinema', 'Cinema/Teatro'), ('lazer_shows', 'Shows/Eventos'), ('lazer_viagens', 'Viagens'), ('lazer_entretenimento', 'Salão de Jogos/Entretenimento'), ('seguros_vida', 'Seguro de Vida'), ('seguros_residencial', 'Seguro Residencial'), ('seguros_viagem', 'Seguro Viagem'), ('pessoais_academia', 'Academia/Atividade Física'), ('pessoais_estetica', 'Estética/Beleza'), ('pessoais_vestuario', 'Vestuário'), ('pessoais_calcados', 'Calçados'), ('pessoais_acessorios', 'Acessórios'), ('familia_mesada', 'Mesada para Filhos'), ('familia_presentes', 'Presentes'), ('familia_pets', 'Cuidados com Pets'), ('contas_telefone', 'Telefone'), ('contas_assinaturas', 'Assinaturas'), ('contas_tv', 'TV por Assinatura/Streaming'), ('investimentos_poupanca', 'Poupança'), ('investimentos_fundos', 'Fundos de Investimento'), ('investimentos_acoes', 'Ações'), ('investimentos_cripto', 'Criptomoedas'), ('impostos_irpf', 'IRPF'), ('impostos_inss', 'INSS'), ('impostos_taxas', 'Taxas/Tributos')], max_length=30, null=True, verbose_name='Subcategoria')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cheque', 'Cheque'), ('outros', 'Outros')], default='dinheiro', max_length=20)),
                ('tipo_pagamento_detalhe', models.CharField(choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], default='avista', max_length=10)),
                ('situacao', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
                ('quantidade_parcelas', models.IntegerField(default=1)),
                ('recorrente', models.CharField(choices=[('unica', 'Única'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='unica', max_length=10)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor da Parcela')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contabancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'unique_together': {('nome', 'categoria', 'usuario')},
            },
        ),
    ]
