# Generated by Django 5.2.5 on 2025-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Deve alterar a senha no próximo login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas deste usuário.', related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='Permissões de usuário'),
        ),
    ]
